name: UpdateCheckerExamplePlugin
main: your.username.pluginname.ExamplePlugin
version: 1.0
api-version: 1.13
commands:
  updatechecker:
    description: "Checks for updates"
    usage: "/<command> [players|all]"
    permission: updatechecker
permissions:
  updatechecker:
    description: "Allows to use the command /updatechecker"
  updatechecker.onjoin:
    description: "Sends a message on join when a new update is available"